language: python
services:
  - postgresql
python:
  - '2.7'
addons:
  postgresql: "9.3"
install:
  - cd app
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database travisci;' -U postgres
  - export ENVIRONMENT=development
  - python manage.py migrate --noinput
  - python manage.py collectstatic --noinput # Add STATIC_ROOT to settings
script:
  - python manage.py test

before_deploy: cd ..

deploy:
  # Deploy master branch to production environment on merge (or push)
  - provider: elasticbeanstalk
    access_key_id: ## ACCESS KEY ID
    secret_access_key:
      secure: ## SECRET ACCESS KEY
    region: us-east-1
    app: django-app-template
    env: djangoAppTemplateProd
    bucket_name: django-app-template-deploy
    bucket_path: production
    skip_cleanup: true
    on:
      repo: thehackerati/django-app-template
      branch: master

  # Deploy staging branch to staging environment on merge (or push)
  - provider: elasticbeanstalk
    access_key_id: ## ACCESS KEY ID
    secret_access_key:
      secure: ## SECRET ACCESS KEY
    region: us-east-1
    app: django-app-template
    env: djangoAppTemplateStg
    bucket_name: django-app-template-deploy
    bucket_path: staging
    skip_cleanup: true
    on:
      repo: thehackerati/django-app-template
      branch: staging
