# Start the node.js application server for local development.
appsvr:
  build: ./app
  volumes:
    - "app:/src/app"
  expose:
    - "3000"
  command: /src/app/start.sh

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "8080:8080"
  volumes:
    - /www/public
  volumes_from:
    - appsvr
  links:
    - appsvr:appsvr
