db:
  image: postgres

appsvr:
  build: ./app
  dockerfile: "Dockerfile.dev"
  volumes:
    - ./app:/src/app/
  links:
    - db

nginx:
  restart: always
  build: ./nginx
  ports:
    - "8000:8000"
  volumes:
    - ./app:/src/app/
  links:
    - appsvr
