db:
  image: postgres

appsvr:
  build: ./app
  # dockerfile: "Dockerfile.dev"
  volumes:
    - /opt/app
  links:
    - db

nginx:
  restart: always
  build: ./nginx
  ports:
    - "8000:8000"
  volumes:
    - /www/public
  volumes_from:
    - appsvr
  links:
    - appsvr:appsvr
